name: digimobile
description: Digimask prototype mobile application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: any
  intl: ^0.16.1
  provider: ^4.3.2+3
  geolocator: ^6.1.13
  flare_flutter: ^2.0.6
  majascan: ^0.3.7
  property_change_notifier: ^0.2.0
  sqflite: ^1.3.2+2
  permission_handler: ^5.0.1+1
  localstorage: ^3.0.6+9
  shared_preferences: ^0.5.12+4

  flutter_easyloading: ^2.2.2
  pull_to_refresh: ^1.6.3
  font_awesome_flutter: ^8.11.0
  animations: ^1.1.2
  flutter_countdown_timer: ^3.0.0
  flutter_local_notifications: ^3.0.3
  no_context_navigation: ^1.0.5
  flutter_launcher_icons: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
